### ISSUE TITLE
Make other fields of an Entry accessible?

### ISSUE THREAD

**Issue by cbreits** [loomanw/robotframework-keepasslibrary#10]
Is it possible to make other fields of an Entry accessible? For example it is possible to to define custom properties in Keepass and those can be accessed via get_custom_property('propertyname') in the pykeepass library. Right now, the only props are username, password, title, etc.

**Comment by loomanw** [comment]
The method for accessing properties of a entry/group is under revisement.

You can however call the method through RF:
*** Settings ***
Library    KeePassLibrary    

*** Test Cases ***
String Filed Demo
    Load Database    Database.kdbx    Password
    ${fieldname}=    Set Variable    field1_name
    ${entry}=    Get Entries By Title    Sample Entry    first=True
    ${field1_value}=    Set Variable     ${entry.get_custom_property('${fieldname}')}
    log to console   ${fieldname} of ${entry} contains ${field1_value}

**Comment by loomanw** [comment]
Update released new related keywords:

`
Get Custom Properties
    [Tags]    Get
    [Documentation]    Selected entry contains expected custom properties.
    ${entry_title}=       Set Variable    root_entry
    ${value_expected}=    Create Dictionary    foobar_attribute=foobar               
    ${entry}=    Get Entries By Title    ${entry_title}    first=True     
    ${value}=    Get Entry Custom Properties    ${entry}
    Dictionaries Should Be Equal    ${value_expected}    ${value} 

Get Custom Property
    [Tags]    Get
    [Documentation]    Selected entry contains expected custom property
    ${entry_title}=           Set Variable    root_entry
    ${entry_property_key}=    Set Variable    foobar_attribute
    ${value_expected}=        Set Variable    foobar
    ${entry}=    Get Entries By Title    ${entry_title}    first=True     
    ${value}=    Get Entry Custom Property    ${entry}    ${entry_property_key}
    Should Be Equal As Strings    ${value_expected}    ${value} `
